### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by worldsoup** [serverless/serverless-azure-functions#3]
- [x] coordinate story for posts
- [x] add docs to serverless.com (https://github.com/serverless/serverless/pull/3274)
- [x] blog post on serverless.com
- [x] blog post on Azure property (draft shared)
- [x] announce on serverless newsletter
- [x] announce on Azure newsletter
- [ ] create 'how to' video
- [x] create Azure example projects (https://github.com/serverless/examples/pull/98)
- [x] <strike>merge dev to master (https://github.com/serverless/serverless-azure-functions/pull/13)</strike>
- [x] <strike>publish npm package (https://github.com/serverless/serverless-azure-functions/issues/14)</strike>
- [x] <strike>`serverless create` template for Azure Functions</strike> Punted since `serverless install` has similar functionality

**Comment by christopheranderson** [comment]
Added PR for docs here: https://github.com/serverless/serverless/pull/3274
Added PR for examples here: https://github.com/serverless/examples/pull/98

I've got the Azure blog post and newsletter items. I'll likely also do a how to video - record my presentation I'm building.

We need to add a `serverless create` template for Azure Functions. Where can we put that?

**Comment by worldsoup** [comment]
@christopheranderson that can be merged in to core, feel free to make the PR!

**Comment by christopheranderson** [comment]
Adding two new items:
 - merge dev to master
 - add npm package

Ideally we could publish the npm package asap so I can update the examples and docs

**Comment by christopheranderson** [comment]
npm package published, will update the other PRs and send out a notice when I believe they are ready to merge

**Comment by mi-hol** [comment]
@christopheranderson @worldsoup   the release 0.1 is out since weeks but the checklist only partially completed. Maybe this should be aligned with 1.0 release?

**Comment by lostintangent** [comment]
Closing this since the plugin is already released, and we can coordinate future milestones with new tracking issues.
